export const actionTypes = {
  SET_SECONDS_AMOUNT: "SET_SECONDS_AMOUNT",
  SELECT_MOVIE: "SELECT_MOVIE",
  CHOOSE_RANDOM_NUMBERS: "CHOOSE_RANDOM_NUMBERS",
  SET_RESULTS: "SET_RESULTS",
  SET_IS_RESULT_VISIBLE: "SET_IS_RESULT_VISIBLE",
  SET_TIME_RANGE: "SET_TIME_RANGE",
};
